<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\DeviceOrder;
use App\Enums\OrderStatus;
use Illuminate\Support\Str;

class DeviceOrderFactory extends Factory
{
    protected $model = DeviceOrder::class;

    public function definition()
    {
        return [
            'branch_id' => 1, // Default test branch
            'device_id' => null, // Should be set via relationship
            'table_id' => null,
            'order_id' => $this->faker->unique()->numberBetween(1000, 9999),
            'order_number' => null, // Auto-generated by model boot()
            'terminal_session_id' => null,
            'session_id' => null,
            'status' => OrderStatus::PENDING,
            'total' => $this->faker->randomFloat(2, 100, 1000),
            'tax' => $this->faker->randomFloat(2, 10, 100),
            'discount' => 0,
            'guest_count' => $this->faker->numberBetween(1, 10),
            'is_printed' => false,
            'printed_at' => null,
            'printed_by' => null,
            // order_uuid auto-generated by model boot() if null
            // subtotal removed - column may not exist in test DB
        ];
    }

    /**
     * Indicate that the order is confirmed.
     */
    public function confirmed()
    {
        return $this->state(fn (array $attributes) => [
            'status' => OrderStatus::CONFIRMED,
        ]);
    }

    /**
     * Indicate that the order is completed.
     */
    public function completed()
    {
        return $this->state(fn (array $attributes) => [
            'status' => OrderStatus::COMPLETED,
        ]);
    }

    /**
     * Indicate that the order is printed.
     */
    public function printed()
    {
        return $this->state(fn (array $attributes) => [
            'is_printed' => true,
            'printed_at' => now(),
            'printed_by' => 'test-printer',
        ]);
    }

    /**
     * Assign the order to a specific device.
     */
    public function forDevice(int $deviceId)
    {
        return $this->state(fn (array $attributes) => [
            'device_id' => $deviceId,
        ]);
    }

    /**
     * Assign the order to a specific table.
     */
    public function forTable(int $tableId)
    {
        return $this->state(fn (array $attributes) => [
            'table_id' => $tableId,
        ]);
    }
}
