<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Device;
use Illuminate\Support\Str;

class DeviceFactory extends Factory
{
    protected $model = Device::class;

    public function definition()
    {
        return [
            'name' => $this->faker->unique()->word() . '-tablet',
            'branch_id' => 1, // Default test branch
            'table_id' => null,
            'is_active' => true,
            'status' => 'online',
            'app_version' => '1.0.0',
            'ip_address' => $this->faker->ipv4(),
            'last_ip_address' => null,
            'last_seen_at' => now(),
            // device_uuid auto-generated by model booted() if null
        ];
    }

    /**
     * Indicate that the device is inactive.
     */
    public function inactive()
    {
        return $this->state(fn (array $attributes) => [
            'is_active' => false,
            'status' => 'offline',
        ]);
    }

    /**
     * Indicate that the device is assigned to a table.
     */
    public function withTable(int $tableId)
    {
        return $this->state(fn (array $attributes) => [
            'table_id' => $tableId,
        ]);
    }

    /**
     * Indicate that the device belongs to a specific branch.
     */
    public function forBranch(int $branchId)
    {
        return $this->state(fn (array $attributes) => [
            'branch_id' => $branchId,
        ]);
    }
}
