/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/token/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Create a new token for the authenticated user */
        get: operations["user.token.create"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all menus */
        get: operations["menus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/with-modifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get menu with modifiers [Set Meal] */
        get: operations["menus.with.modifiers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/modifier-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all modifier groups
         * @description Returns all modifier groups. Adding a query param of modifiers = 1 will include the modifiers in the response
         */
        get: operations["menus.modifier-groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/modifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all menu modifiers
         * @description List of all menu modifiers like P1, P2, P3, P4, P5.
         */
        get: operations["menus.modifiers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all menus for the given course */
        get: operations["menus.by.course"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all menus for the given group */
        get: operations["menus.by.group"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/group-raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return raw stored-proc output for a POS group (calls `get_menus_by_group`)
         * @description Query params:
         *     - group: string (optional) POS group name, defaults to 'Meat Order'
         *
         *     This returns the raw rows the stored procedure emits. Useful for clients
         *     that need the exact POS-provided structure (menuName, groupName, computed_modifiers, etc.).
         */
        get: operations["menus.group.raw"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/modifiers-by-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return modifiers grouped by meat type (Pork/Beef/Chicken) for a POS menu group
         * @description Query params:
         *     - group: string (optional) POS group name, defaults to 'Meat Order'
         *
         *     Response: object with keys 'Pork','Beef','Chicken' mapping to arrays of modifiers.
         */
        get: operations["menus.modifiers.by.grouped"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/package-modifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return exact modifiers for a package menu by package id
         * @description Accepts a single parameter `package_id` (integer). For packages 46,47,48
         *     this will return the exact modifiers selected by `Menu::getModifiers()`
         *     which uses `receipt_name` codes (P*, B*, C*).
         */
        get: operations["menus.package.modifiers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all menus for the given category */
        get: operations["menus.by.category"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a list of all devices */
        get: operations["devices.index"];
        put?: never;
        /** Store a newly created device in storage */
        post: operations["devices.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display the specified device */
        get: operations["devices.show"];
        /** Update the specified device */
        put: operations["devices.update"];
        post?: never;
        /** Remove the specified device from storage */
        delete: operations["devices.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device/table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find the device (and its table) by the authenticated device or by IP
         * @description Behaviour: If the request is authenticated as a device, use that device.
         *     Otherwise, use the optional `ip_address` query param or the request IP
         *     to find an active device record.
         *
         *     Response: { success: true, device_id, table: { id, name } } or 404.
         */
        get: operations["device.table"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login a device */
        get: operations["devices.login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a device */
        post: operations["devices.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current token and issue a new one with the same
         *     abilities and expiration time
         */
        post: operations["devices.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the token of the device that made the request and logout */
        post: operations["devices.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/create-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Handle the incoming order request from a specific device */
        post: operations["devices.create.order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Menu Selections
         * @description This endpoint will return a list of all menu items available for selection.
         */
        get: operations["menu.menuBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/{orderId}/refill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist refill items and dispatch print event */
        post: operations["orderApi.refill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/{orderId}/printed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a device order as printed */
        post: operations["orderApi.markPrinted"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device-order/{order}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display the specified resource */
        get: operations["orderApi.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/device-order/by-order-id/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show the specified resource by external order_id field */
        get: operations["orderApi.showByExternalId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/printer/unprinted-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return unacknowledged PrintEvents for printers to consume */
        get: operations["printerApi.getUnprintedEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/printer/print-events/{id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge a PrintEvent as handled by a printer */
        post: operations["printerApi.ackPrintEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/printer/print-events/{id}/failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a PrintEvent as failed (printer reported error) */
        post: operations["printerApi.failPrintEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/printer/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["printerApi.heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/printed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["printerApi.markPrinted"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/printed/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["printerApi.markPrintedBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sends a service request to the server
         *     and broadcasts the event
         */
        post: operations["service.request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a list of all services */
        get: operations["tables.services"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session.latest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Branch */
        Branch: string[];
        /** DeviceOrder */
        DeviceOrder: string[];
        /** DeviceOrderResource */
        DeviceOrderResource: {
            id: string;
            order_id: string;
            order_number: string;
            device: components["schemas"]["DeviceResource"];
            order: components["schemas"]["Order"];
            table: string;
            tablename: string;
            status: string;
            /** @description Expose monetary fields so clients (devices/clients) can display totals immediately */
            subtotal: string;
            tax: string;
            discount: string;
            total: string;
            guest_count: string;
            is_printed: string;
            printed_at: string;
            printed_by: string;
            items: string;
            print_events?: string;
        };
        /** DeviceRegisterRequest */
        DeviceRegisterRequest: {
            name: string;
            code: string;
            app_version?: string | null;
        };
        /** DeviceResource */
        DeviceResource: {
            id: string;
            device_uuid: string;
            branch: components["schemas"]["Branch"];
            name: string;
            table: string;
        };
        /** MarkOrderPrintedBulkRequest */
        MarkOrderPrintedBulkRequest: {
            /** Format: date-time */
            printed_at?: string | null;
            printer_id?: string | null;
            order_ids: number[];
        };
        /** MarkOrderPrintedRequest */
        MarkOrderPrintedRequest: {
            /** Format: date-time */
            printed_at?: string | null;
            printer_id?: string | null;
        };
        /** MenuModifierResource */
        MenuModifierResource: {
            id: string;
            /** @description Preserve existing relation-based group name */
            group: string;
            /** @description POS/group label derived from `receipt_name` (P=Pork, B=Beef, C=Chicken) */
            groupName: null | string | ("Pork" | "Beef" | "Chicken");
            name: string;
            category: string;
            kitchen_name: string;
            receipt_name: string;
            price: string;
            /** @description 'cost' => Number::format($this->cost ?? 0, 2), */
            description: string;
            is_taxable: string;
            is_available: string;
            is_discountable: string;
            /**
             * @description 'tare_weight' => $this->tare_weight,
             *     'scale_unit' => $this->scale_unit,
             *     'measurement_unit' => $this->measurement_unit,
             *     'is_locked' => $this->is_locked,
             *     'quantity' => $this->quantity,
             */
            is_modifier: string;
            is_modifier_only: string;
            isMod: string;
            isModOnly: string;
            img_url: string;
        };
        /** MenuResource */
        MenuResource: {
            id: string;
            /**
             * @description 'menu_group_id' => $this->menu_group_id ?? null,
             *     'menu_category_id' => $this->menu_category_id ?? null,
             *     'menu_course_type_id' => $this->menu_course_type_id ?? null,
             *     'menu_tax_type_id' => $this->menu_tax_type_id ?? null,
             */
            group: string;
            /** @description POS/raw fields (some stored-procs return these exact keys) */
            groupName: string;
            category: string;
            course: string;
            name: string;
            kitchen_name: string;
            receipt_name: string;
            price: string;
            cost: string;
            /**
             * @description 'description' => $this->description,
             *     'index' => $this->index,
             */
            is_taxable: string;
            /** @description 'is_available' => $this->is_available, */
            is_modifier: string;
            is_modifier_only: string;
            /** @description Legacy/pos keys for clients that use camelCase flags */
            isMod: string;
            isModOnly: string;
            /** @description 'can_open_price' => $this->can_open_price, */
            is_discountable: string;
            /**
             * @description 'tare_weight' => $this->tare_weight,
             *     'scale_unit' => $this->scale_unit,
             *     'measurement_unit' => $this->measurement_unit,
             *     'auto_counter' => $this->auto_counter,
             *     'is_locked' => $this->is_locked,
             *     'quantity' => $this->quantity,
             *     'in_stock' => $this->in_stock,
             *     'prompt_for_note' => $this->prompt_for_note,
             *     'is_modifier_only' => $this->is_modifier_only,
             *     'container_id' => $this->container_id,
             *     'quantity_option' => $this->quantity_option,
             *     'units' => $this->units,
             *     'show_unit_price_on_receipt' => $this->show_unit_price_on_receipt,
             *     'decimal_places_for_qty_input' => $this->decimal_places_for_qty_input,
             *     'prompt_description' => $this->prompt_description,
             *     'serving_count' => $this->serving_count,
             *     'best_seller_candidate' => $this->best_seller_candidate,
             *     'calories' => $this->calories,
             *     'guest_count' => $this->guest_count,
             */
            img_url: string;
            /**
             * @description 'image' => $this->image?->path,
             *     'images' => $this->menuImage,
             *     'img_path' => $this->image_url,
             */
            tax: string;
            tax_amount: string;
            modifiers?: components["schemas"]["MenuModifierResource"][];
        };
        /** Order */
        Order: {
            id: number;
            session_id: number;
            terminal_session_id: number;
            date_time_opened: string;
            date_time_closed: string | null;
            revenue_id: number;
            terminal_id: number;
            current_terminal_id: number | null;
            end_terminal_id: number | null;
            customer_id: number | null;
            is_open: boolean;
            is_transferred: boolean;
            is_voided: boolean;
            guest_count: number;
            service_type_id: number;
            is_available: boolean;
            cash_tray_session_id: number | null;
            server_banking_session_id: number | null;
            start_employee_log_id: number;
            current_employee_log_id: number | null;
            close_employee_log_id: number | null;
            server_employee_log_id: number | null;
            transaction_no: number | null;
            reference: string;
            created_on: string | null;
            modified_on: string | null;
            cashier_employee_id: number | null;
            terminal_service_id: number | null;
            is_online_order: boolean | null;
            reprint_count: number;
        };
        /** PrinterHeartbeatRequest */
        PrinterHeartbeatRequest: {
            printer_id: string;
            printer_name?: string | null;
            bluetooth_address?: string | null;
            app_version?: string | null;
            session_id?: number | null;
            last_printed_order_id?: number | null;
            /** Format: date-time */
            timestamp?: string | null;
        };
        /** ServiceRequestResource */
        ServiceRequestResource: {
            id: string;
            order_id: string;
            table_service_id: string;
            created_at: string;
        };
        /** StoreDeviceOrderRequest */
        StoreDeviceOrderRequest: {
            /** @example 2 */
            guest_count: number;
            /** @example 988 */
            subtotal: number;
            /** @example 118.56 */
            tax: number;
            /** @example 0 */
            discount: number;
            /** @example 1106.56 */
            total_amount: number;
            /**
             * @example [
             *       {
             *         "menu_id": 46,
             *         "name": "Classic Feast",
             *         "quantity": 2,
             *         "price": 399,
             *         "note": "this is a note",
             *         "subtotal": 898,
             *         "tax": 107.76,
             *         "discount": 0
             *       },
             *       {
             *         "menu_id": 96,
             *         "name": "Coke Zero",
             *         "quantity": 2,
             *         "price": 45,
             *         "note": "this is a note",
             *         "subtotal": 90,
             *         "tax": 10.8,
             *         "discount": 0
             *       }
             *     ]
             */
            items: {
                menu_id: number;
                name: string;
                quantity: number;
                price: number;
                note?: string | null;
                subtotal: number;
                tax?: number | null;
                discount?: number | null;
            }[];
        };
        /** StoreDeviceRequest */
        StoreDeviceRequest: {
            name: string;
            ip_address: string;
            port?: number | null;
            table_id?: number | null;
        };
        /** StoreServiceRequest */
        StoreServiceRequest: {
            table_service_id: number;
            order_id: number;
        };
        /** TableResource */
        TableResource: {
            id: string;
            name: string;
        };
        /** UpdateDeviceRequest */
        UpdateDeviceRequest: {
            name: string;
            ip_address: string;
            port?: number | null;
            table_id?: number | null;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "user.token.create": {
        parameters: {
            query: {
                email: string;
                password: string;
                device_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    menus: {
        parameters: {
            query?: {
                /** @example 1 */
                menu_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string | components["schemas"]["MenuResource"];
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "menus.with.modifiers": {
        parameters: {
            query?: {
                /** @example 1 */
                menu_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `MenuResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResource"][] | components["schemas"]["MenuResource"];
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "menus.modifier-groups": {
        parameters: {
            query?: {
                /** @example 1 */
                modifiers?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "menus.modifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `MenuModifierResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuModifierResource"][];
                };
            };
        };
    };
    "menus.by.course": {
        parameters: {
            query: {
                /** @example starter */
                course: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `MenuResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResource"][];
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "menus.by.group": {
        parameters: {
            query: {
                /** @example Sides */
                group: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `MenuResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResource"][];
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "menus.group.raw": {
        parameters: {
            query?: {
                group?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rows: string[];
                        ids: string[];
                        packages: string[];
                    } | {
                        rows: string;
                        ids: string;
                        packages: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Failed to fetch group rows";
                        error: string;
                    };
                };
            };
        };
    };
    "menus.modifiers.by.grouped": {
        parameters: {
            query?: {
                group?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    "menus.package.modifiers": {
        parameters: {
            query: {
                package_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `MenuModifierResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuModifierResource"][];
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "menus.by.category": {
        parameters: {
            query: {
                /** @example beverage */
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `MenuResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResource"][];
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "devices.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `DeviceResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResource"][];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "devices.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreDeviceRequest"];
            };
        };
        responses: {
            /** @description `DeviceResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "devices.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The device ID */
                device: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `DeviceResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "devices.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The device ID */
                device: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceRequest"];
            };
        };
        responses: {
            /** @description `DeviceResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "devices.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The device ID */
                device: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "device.table": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "OK";
                        data: {
                            device: components["schemas"]["DeviceResource"];
                            table: components["schemas"]["TableResource"] | null;
                            ip_used: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Device not found";
                    };
                };
            };
        };
    };
    "devices.login": {
        parameters: {
            query?: {
                /** @description Prefer client-supplied ip_address when private, otherwise request->ip() */
                ip_address?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        token: string;
                        device: string;
                        table: string;
                        expires_at: string;
                        ip_used: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        error: "Device not found";
                        ip_address: string;
                    };
                };
            };
        };
    };
    "devices.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeviceRegisterRequest"] & {
                    /** @description Prefer client-supplied ip_address when it looks like a LAN/private IP. */
                    ip_address?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        token: string;
                        device: Record<string, never>;
                        table: string;
                        expires_at: string;
                        ip_used: string;
                    };
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Device already registered";
                        device: string;
                        ip_used: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "devices.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        token: string;
                        device: string;
                        table: string;
                        expires_at: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "devices.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        message: "Successfully logged out";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "devices.create.order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreDeviceOrderRequest"];
            };
        };
        responses: {
            /**
             * @description PrintOrder::dispatch($order);
             *     $this->printKitchen($order->order_id);
             *     app(BroadcastService::class)->dispatchBroadcastJob(new OrderCreated($order));
             *     PrinterOrderJob::dispatch($order, 'cashier')->onQueue('cashier');
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        order: components["schemas"]["DeviceOrderResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "An existing order (pending or confirmed) prevents creating a new order for this device.";
                        order: components["schemas"]["DeviceOrderResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Order processing failed.";
                        errors: string[];
                    };
                };
            };
        };
    };
    "menu.menuBundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description $packages = MenuRepository::getMenusWithModifiers();
             *     if ($packages->isEmpty()) {
             *     $packages = Menu::with('modifiers')
             *     ->whereIn('id', [46, 47, 48])
             *     ->get();
             *     }
             *     Load modifiers
             *     $packages->load('modifiers');
             *     $sides = $this->getMenusByGroup('Sides');
             *     $desserts = $this->getMenusByCategory('Dessert');
             *     $beverages = $this->getMenusByCategory('Beverage');
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        packages: unknown[] | null;
                    };
                };
            };
        };
    };
    "orderApi.refill": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    items: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        created: Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Order not found";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Failed to persist refill";
                        error: string;
                    };
                };
            };
        };
    };
    "orderApi.markPrinted": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Order not found";
                    };
                };
            };
        };
    };
    "orderApi.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order ID */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        order: components["schemas"]["DeviceOrder"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "orderApi.showByExternalId": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        order: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Order not found";
                    };
                };
            };
        };
    };
    "printerApi.getUnprintedEvents": {
        parameters: {
            query?: {
                since?: string;
                session_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        count: string;
                        events: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "printerApi.ackPrintEvent": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    printer_id?: string;
                    printed_at?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Acknowledged";
                        data: {
                            id: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Event not found";
                    };
                };
            };
        };
    };
    "printerApi.failPrintEvent": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    error?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Marked failed";
                        data: {
                            id: string;
                            attempts: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Event not found";
                    };
                };
            };
        };
    };
    "printerApi.heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrinterHeartbeatRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Heartbeat received";
                        data: {
                            server_time: string;
                            session_active: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "printerApi.markPrinted": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MarkOrderPrintedRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Order marked as printed";
                        data: {
                            order_id: string;
                            is_printed: string;
                            printed_at: string;
                        };
                    } | {
                        success: boolean;
                        /** @enum {string} */
                        message: "Order was already printed";
                        data: {
                            order_id: string;
                            is_printed: string;
                            printed_at: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Forbidden";
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Order not found";
                        data: null;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "printerApi.markPrintedBulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkOrderPrintedBulkRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data: {
                            updated: string[];
                            already_printed: string[];
                            not_found: string[];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "service.request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreServiceRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Service sent successfully";
                        data: {
                            service_request: components["schemas"]["ServiceRequestResource"];
                        };
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Service request could not be sent";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Unauthorized to request service for this order";
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Device order not found";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        /** @enum {string} */
                        message: "Failed to send service request";
                    };
                };
            };
        };
    };
    "tables.services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "session.latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
}
